[package]
name = "as_u8_slice_derive"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
