name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Maybe useful update
        run: sudo apt update

      - name: get APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: glslc
          execute_install_scripts: true

      - name: Setup Rust
        run: rustup component add rust-src

      - name: Build demo Vulkan
        run: cargo +nightly biv
      - name: Build demo WGPU
        run: cargo +nightly biw

    # there is not much to test, its a renderer after all
