[alias]
# just shorter alias... saves 1 character!!!
nv = "rnv"
nw = "rnw"
rnv = "run -Zbuild-std=std,panic_abort --profile native --package demo --bin demo_vk --features vk_backend"
rnw = "run -Zbuild-std=std,panic_abort --profile native --package demo --bin demo_wgpu --features wgpu_backend"
bnv = "build -Zbuild-std=std,panic_abort --profile native --package demo --bin demo_vk --features vk_backend"
bnw = "build -Zbuild-std=std,panic_abort --profile native --package demo --bin demo_wgpu --features wgpu_backend"

iv = "riv"
iw = "riw"
riv = "run -Zbuild-std=std,panic_abort --profile distribution --package demo --bin demo_vk --features vk_backend"
riw = "run -Zbuild-std=std,panic_abort --profile distribution --package demo --bin demo_wgpu --features wgpu_backend"
biv = "build -Zbuild-std=std,panic_abort --profile distribution --package demo --bin demo_vk --features vk_backend"
biw = "build -Zbuild-std=std,panic_abort --profile distribution --package demo --bin demo_wgpu --features wgpu_backend"

rv = "rrv"
rw = "rrw"
rrv = "run --profile release --package demo --bin demo_vk --features vk_backend"
rrw = "run --profile release --package demo --bin demo_wgpu --features wgpu_backend"
brv = "build --profile release --package demo --bin demo_vk --features vk_backend"
brw = "build --profile release --package demo --bin demo_wgpu --features wgpu_backend"

dv = "rdv"
dw = "rdw"
rdv = "run --profile dev --package demo --bin demo_vk --features vk_backend"
rdw = "run --profile dev --package demo --bin demo_wgpu --features wgpu_backend"
bdv = "build --profile dev --package demo --bin demo_vk --features vk_backend"
bdw = "build --profile dev --package demo --bin demo_wgpu --features wgpu_backend"

[build]
[target.'cfg(target_arch="wasm32")'.profile.dev]
rustflags = ["--cfg=web_sys_unstable_apis"]

[env]
RUST_BACKTRACE = "short" # this is what i love in Rust

# native is highest perfomance build
[profile.native.build-override]
rustflags = [
    "-C",
    "target-cpu=native",
    # TODO: find better passes for Lum 
    # "-C",
    # "passes= adce loop-unroll simplifycfg gvn sroa tailcallelim early-cse",
]

# natsize is smallest build
[profile.natsize.build-override]
rustflags = [
    "-C",
    "target-cpu=native",
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
]

[unstable]
codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

# to disable some llvm wasm features that break my current tooling (e.g. wasm-opt)
[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-cpu=mvp"]
