name: Deploy Static Assets

permissions:
  contents: write

on:
  push:
    paths:
      - "index.html"
      - "styles.css"
      - "articles/**"
      - "media/**"
      - "projects/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1

      - name: Gather files
        run: |
          rm -rf deploy
          mkdir deploy
          cp index.html styles.css deploy/
          cp -r articles media projects deploy/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
          keep_files: true
